import "dotenv/config";
import crypto from "node:crypto";
import express from "express";
import helmet from "helmet";
import cookieSession from "cookie-session";
import cron from "node-cron";
import { DateTime } from "luxon";
import { createRequire } from "node:module";
import { cert, getApps, initializeApp } from "firebase-admin/app";
import { getDatabase } from "firebase-admin/database";

const require = createRequire(import.meta.url);
const { Client: UnbClient } = require("unb-api");

const need = n => { const v=process.env[n]; if(!v) throw new Error(`Missing ${n}`); return v; };
const nenv = (n,d) => process.env[n] === undefined ? d : Number(process.env[n]);
const cfg = {
  port: nenv("PORT",3000), baseUrl: need("PUBLIC_BASE_URL").replace(/\/$/,""), sessionSecret: need("SESSION_SECRET"),
  discord:{clientId:need("DISCORD_CLIENT_ID"),clientSecret:need("DISCORD_CLIENT_SECRET"),redirectUri:need("DISCORD_REDIRECT_URI"),guildId:need("DISCORD_GUILD_ID"),admins:new Set((process.env.ADMIN_DISCORD_IDS||"").split(",").map(x=>x.trim()).filter(Boolean))},
  unb:{token:need("UNBELIEVABOAT_API_TOKEN"),guildId:need("UNBELIEVABOAT_GUILD_ID"),itemId:need("UNBELIEVABOAT_STOCK_ITEM_ID")},
  firebase:{projectId:need("FIREBASE_PROJECT_ID"),clientEmail:need("FIREBASE_CLIENT_EMAIL"),privateKey:need("FIREBASE_PRIVATE_KEY").replace(/\\n/g,"\n"),databaseURL:need("FIREBASE_DATABASE_URL"),rootPath:process.env.FIREBASE_ROOT_PATH||"ussrSocialistStockMarket"},
  statsSecret:need("STATS_INGEST_SECRET"), timezone:process.env.MARKET_TIMEZONE||"Europe/Brussels",
  closeMinutes:nenv("NORMAL_CLOSURE_MINUTES",60), maxCloseMinutes:nenv("MAX_CLOSURE_MINUTES",120),
  startPrice:nenv("STARTING_STOCK_PRICE",100), totalShares:nenv("TOTAL_ISSUED_SHARES",200000), treasury:nenv("TREASURY_RESERVE",195000), available:nenv("PUBLIC_AVAILABLE_SHARES",5000), citizenLimit:nenv("CITIZEN_SHARE_LIMIT",200), maxDaily:nenv("MAX_DAILY_PERCENT",3), minDaily:nenv("MIN_DAILY_PERCENT",-3)
};
if(!getApps().length) initializeApp({credential:cert({projectId:cfg.firebase.projectId,clientEmail:cfg.firebase.clientEmail,privateKey:cfg.firebase.privateKey}),databaseURL:cfg.firebase.databaseURL});
const root=getDatabase().ref(cfg.firebase.rootPath);
const unb=new UnbClient(cfg.unb.token);
const app=express(); app.set("trust proxy",1); app.use(helmet({contentSecurityPolicy:false})); app.use(express.json({limit:"100kb"})); app.use(cookieSession({name:"ussr_stock",keys:[cfg.sessionSecret],httpOnly:true,secure:true,sameSite:"lax",maxAge:604800000})); app.use(express.static("public"));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const r2=v=>Math.round(v*100)/100;

async function init(){const s=await root.once("value"); if(s.exists()) return; await root.set({market:{status:"closed",price:cfg.startPrice,sessionOpenPrice:cfg.startPrice,changePercent:0,openedAt:null,closesAt:null,reopensAt:null},shares:{totalIssued:cfg.totalShares,treasuryReserve:cfg.treasury,available:cfg.available,citizenLimit:cfg.citizenLimit},statistics:{membersOnline:0,membersOffline:0,joins:0,leaves:0,boosts:0,messagesSent:0,capturedAt:Date.now()},warning:{enabled:true,author:"hyawii2.0 — State Committee of Economy",text:"Stock prices can rise or fall. Citizens may lose rubles. Past performance does not guarantee future results. Only invest rubles you can afford to lose."},announcements:{}});}
function requireLogin(req,res,next){if(!req.session?.user?.id)return res.status(401).json({error:"Discord login required."});next();}
function requireAdmin(req,res,next){if(!req.session?.user?.id||!cfg.discord.admins.has(req.session.user.id))return res.status(403).json({error:"Administrator access required."});next();}
function requireStats(req,res,next){const got=Buffer.from(String(req.get("x-stats-secret")||""));const want=Buffer.from(cfg.statsSecret);if(got.length!==want.length||!crypto.timingSafeEqual(got,want))return res.status(401).json({error:"Invalid statistics secret."});next();}
async function discordToken(code){const b=new URLSearchParams({client_id:cfg.discord.clientId,client_secret:cfg.discord.clientSecret,grant_type:"authorization_code",code,redirect_uri:cfg.discord.redirectUri});const r=await fetch("https://discord.com/api/v10/oauth2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:b});if(!r.ok)throw new Error("Discord token exchange failed");return r.json();}
async function discordGet(path,token){const r=await fetch(`https://discord.com/api/v10${path}`,{headers:{authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Discord ${path} failed`);return r.json();}
function movement(st){const online=Number(st.membersOnline||0),offline=Number(st.membersOffline||0),members=Math.max(1,online+offline),messages=Number(st.messagesSent||0),joins=Number(st.joins||0),leaves=Number(st.leaves||0),boosts=Number(st.boosts||0);const activity=clamp(Math.log10(messages+1)/4,0,1),presence=clamp((online/members-.08)/.32,-.25,1),flow=clamp((joins-leaves)/Math.max(10,members*.02),-1,1),boost=clamp(boosts/5,0,1);const raw=activity*.9+presence*.65+flow*.75+boost*.35-.55;return r2(clamp(Math.tanh(raw)*2.25,cfg.minDaily,cfg.maxDaily));}
async function openMarket(){const now=DateTime.now().setZone(cfg.timezone),m=(await root.child("market").once("value")).val()||{},price=Number(m.price||cfg.startPrice);await root.update({"market/status":"open","market/sessionOpenPrice":price,"market/changePercent":0,"market/openedAt":now.toMillis(),"market/closesAt":now.plus({hours:24}).toMillis(),"market/reopensAt":null,"statistics/joins":0,"statistics/leaves":0,"statistics/boosts":0,"statistics/messagesSent":0});}
async function settle(){const d=(await root.once("value")).val()||{},m=d.market||{},st=d.statistics||{},open=Number(m.sessionOpenPrice||m.price||cfg.startPrice),pct=movement(st),price=r2(Math.max(1,open*(1+pct/100))),abnormal=Math.abs(Number(st.joins||0)-Number(st.leaves||0))>=20||Number(st.messagesSent||0)>=25000,mins=abnormal?cfg.maxCloseMinutes:cfg.closeMinutes,now=DateTime.now().setZone(cfg.timezone);await root.update({"market/status":"closed","market/price":price,"market/changePercent":pct,"market/reopensAt":now.plus({minutes:mins}).toMillis(),"market/closesAt":null,[`history/${now.toFormat("yyyy-LL-dd-HHmm")}`]:{openPrice:open,closePrice:price,changePercent:pct,statistics:st,settledAt:now.toMillis()}});}

app.get("/auth/discord",(req,res)=>{const state=crypto.randomBytes(20).toString("hex");req.session.oauthState=state;const q=new URLSearchParams({client_id:cfg.discord.clientId,redirect_uri:cfg.discord.redirectUri,response_type:"code",scope:"identify guilds.members.read",state});res.redirect(`https://discord.com/oauth2/authorize?${q}`);});
app.get("/auth/discord/callback",async(req,res)=>{try{if(!req.query.code||req.query.state!==req.session.oauthState)return res.status(400).send("Invalid OAuth state.");const t=await discordToken(String(req.query.code));await discordGet(`/users/@me/guilds/${cfg.discord.guildId}/member`,t.access_token);const u=await discordGet("/users/@me",t.access_token);req.session.user={id:u.id,username:u.global_name||u.username,avatar:u.avatar,isAdmin:cfg.discord.admins.has(u.id)};delete req.session.oauthState;res.redirect("/");}catch(e){console.error(e);res.status(403).send("Discord login failed or you are not in the server.");}});
app.post("/auth/logout",(req,res)=>{req.session=null;res.json({ok:true});});
app.get("/api/session",(req,res)=>res.json({user:req.session?.user||null}));
app.get("/api/public/market",async(req,res)=>{const d=(await root.once("value")).val()||{};res.json({market:d.market||{},shares:d.shares||{},statistics:d.statistics||{},warning:d.warning||{},announcements:d.announcements||{},history:d.history||{}});});
app.get("/api/portfolio",requireLogin,async(req,res)=>{try{const [bal,inv,m]=await Promise.all([unb.getUserBalance(cfg.unb.guildId,req.session.user.id),unb.getInventoryItems(cfg.unb.guildId,req.session.user.id,{limit:100}),root.child("market").once("value")]);const item=(inv.items||[]).find(x=>String(x.itemId||x.item_id)===String(cfg.unb.itemId)),qty=Number(item?.quantity||0),price=Number(m.val()?.price||0);res.json({cash:Number(bal.cash||0),bank:Number(bal.bank||0),total:Number(bal.total||0),shares:qty,price,marketValue:r2(qty*price)});}catch(e){console.error(e);res.status(502).json({error:"Unable to read your UnbelievaBoat balance or inventory."});}});
async function withLock(uid,fn){const ref=root.child(`tradeLocks/${uid}`),r=await ref.transaction(v=>v?undefined:{at:Date.now()});if(!r.committed)throw Object.assign(new Error("Another trade is processing."),{status:429});try{return await fn();}finally{await ref.remove();}}
app.post("/api/trade/buy",requireLogin,async(req,res)=>{try{const out=await withLock(req.session.user.id,async()=>{const q=Math.trunc(Number(req.body.quantity));if(!Number.isInteger(q)||q<1||q>cfg.citizenLimit)throw Object.assign(new Error("Invalid quantity."),{status:400});const [ms,ss,bal,inv]=await Promise.all([root.child("market").once("value"),root.child("shares").once("value"),unb.getUserBalance(cfg.unb.guildId,req.session.user.id),unb.getInventoryItems(cfg.unb.guildId,req.session.user.id,{limit:100})]);const m=ms.val()||{},sh=ss.val()||{},owned=Number((inv.items||[]).find(x=>String(x.itemId||x.item_id)===String(cfg.unb.itemId))?.quantity||0);if(m.status!=="open")throw Object.assign(new Error("Market is closed."),{status:409});if(owned+q>Number(sh.citizenLimit||cfg.citizenLimit))throw Object.assign(new Error("Citizen share limit exceeded."),{status:409});if(q>Number(sh.available||0))throw Object.assign(new Error("Not enough shares available."),{status:409});const price=Number(m.price||0),cost=Math.ceil(price*q);if(Number(bal.cash||0)<cost)throw Object.assign(new Error("Not enough cash. Bank money is not used automatically."),{status:409});await unb.editUserBalance(cfg.unb.guildId,req.session.user.id,{cash:-cost,bank:0},`Bought ${q} Red Star shares`);try{await unb.addInventoryItem(cfg.unb.guildId,req.session.user.id,cfg.unb.itemId,q);}catch(e){await unb.editUserBalance(cfg.unb.guildId,req.session.user.id,{cash:cost,bank:0},"Automatic stock purchase refund");throw e;}await root.child("shares/available").transaction(v=>Math.max(0,Number(v||0)-q));await root.child("trades").push({type:"buy",userId:req.session.user.id,quantity:q,price,total:cost,createdAt:Date.now()});return{quantity:q,price,total:cost};});res.json({ok:true,...out});}catch(e){console.error(e);res.status(e.status||502).json({error:e.message||"Trade failed."});}});
app.post("/api/trade/sell",requireLogin,async(req,res)=>{try{const out=await withLock(req.session.user.id,async()=>{const q=Math.trunc(Number(req.body.quantity));if(!Number.isInteger(q)||q<1||q>cfg.citizenLimit)throw Object.assign(new Error("Invalid quantity."),{status:400});const [ms,inv]=await Promise.all([root.child("market").once("value"),unb.getInventoryItems(cfg.unb.guildId,req.session.user.id,{limit:100})]);const m=ms.val()||{},owned=Number((inv.items||[]).find(x=>String(x.itemId||x.item_id)===String(cfg.unb.itemId))?.quantity||0);if(m.status!=="open")throw Object.assign(new Error("Market is closed."),{status:409});if(owned<q)throw Object.assign(new Error("You do not own enough shares."),{status:409});const price=Number(m.price||0),pay=Math.floor(price*q);await unb.removeInventoryItem(cfg.unb.guildId,req.session.user.id,cfg.unb.itemId,q);try{await unb.editUserBalance(cfg.unb.guildId,req.session.user.id,{cash:pay,bank:0},`Sold ${q} Red Star shares`);}catch(e){await unb.addInventoryItem(cfg.unb.guildId,req.session.user.id,cfg.unb.itemId,q);throw e;}await root.child("shares/available").transaction(v=>Math.min(cfg.available,Number(v||0)+q));await root.child("trades").push({type:"sell",userId:req.session.user.id,quantity:q,price,total:pay,createdAt:Date.now()});return{quantity:q,price,total:pay};});res.json({ok:true,...out});}catch(e){console.error(e);res.status(e.status||502).json({error:e.message||"Trade failed."});}});
app.post("/api/internal/server-statistics",requireStats,async(req,res)=>{const keys=["membersOnline","membersOffline","joins","leaves","boosts","messagesSent"],u={capturedAt:Date.now()};for(const k of keys){const v=Number(req.body[k]);if(!Number.isFinite(v)||v<0)return res.status(400).json({error:`Invalid ${k}`});u[k]=Math.trunc(v);}await root.child("statistics").update(u);res.json({ok:true});});
app.patch("/api/admin/market",requireAdmin,async(req,res)=>{const u={};if(Number.isFinite(Number(req.body.price)))u.price=Math.max(1,r2(Number(req.body.price)));if(Number.isFinite(Number(req.body.changePercent)))u.changePercent=clamp(Number(req.body.changePercent),-99,999);if(req.body.status==="open"||req.body.status==="closed")u.status=req.body.status;await root.child("market").update(u);res.json({ok:true});});
app.patch("/api/admin/warning",requireAdmin,async(req,res)=>{await root.child("warning").update({enabled:Boolean(req.body.enabled),text:String(req.body.text||"").slice(0,1200),author:"hyawii2.0 — State Committee of Economy"});res.json({ok:true});});
app.post("/api/admin/open",requireAdmin,async(req,res)=>{await openMarket();res.json({ok:true});}); app.post("/api/admin/settle",requireAdmin,async(req,res)=>{await settle();res.json({ok:true});});
app.get("/health",(req,res)=>res.send("OK"));
cron.schedule("* * * * *",async()=>{try{const now=DateTime.now().setZone(cfg.timezone),m=(await root.child("market").once("value")).val()||{};if(m.status==="open"&&m.closesAt&&now.toMillis()>=Number(m.closesAt))await settle();else if(m.status==="closed"&&m.reopensAt&&now.toMillis()>=Number(m.reopensAt))await openMarket();}catch(e){console.error("scheduler",e);}}, {timezone:cfg.timezone});
await init(); app.listen(cfg.port,"0.0.0.0",()=>console.log(`Running: ${cfg.baseUrl}; public API: ${cfg.baseUrl}/api/public/market`));
